import { motion } from 'framer-motion'
import { AlertTriangle, ArrowDownRight, BrainCircuit, ChevronRight, ShieldCheck } from 'lucide-react'
import { GlobalAttackMap } from '@/components/GlobalAttackMap'

const events = [
  ['185.220.101.4', 'RDP brute force', 'EDGE-RDP-01', 'critical'],
  ['103.28.41.17', 'Web exploitation', 'API-GATEWAY-02', 'high'],
  ['177.84.11.29', 'SSH anomaly', 'BASTION-01', 'medium'],
] as const

export function CommandCenterPage() {
  return <div className="min-h-full bg-[#090909] px-4 py-5 text-stone-100 md:px-7 md:py-7">
    <div className="mb-7 flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-stone-500">Golden Dome / command center</p><h1 className="mt-2 text-2xl font-medium tracking-tight">Security overview</h1></div><p className="hidden text-xs text-stone-500 md:block">Tuesday, 27 July · <span className="text-emerald-400">Systems operational</span></p></div>
    <div className="grid gap-0 overflow-hidden border border-white/[.08] bg-[#0d0f0f] xl:grid-cols-[250px_minmax(0,1fr)_290px]">
      <aside className="border-b border-white/[.08] p-5 xl:border-b-0 xl:border-r"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-stone-500">Security posture</p><div className="mt-8"><p className="text-5xl font-medium tracking-tighter">72<span className="text-xl text-stone-600">/100</span></p><p className="mt-2 text-sm text-[#c97948]">Elevated exposure</p></div><div className="mt-10 space-y-5">{[['Critical alerts','04','#b94747'],['Active incidents','07','#c97929'],['Protected assets','128','#6ee7b7']].map(([label,value,color]) => <div key={label}><p className="text-[11px] text-stone-500">{label}</p><p className="mt-1 text-xl font-medium" style={{ color }}>{value}</p></div>)}</div><button className="mt-10 flex items-center gap-2 text-xs text-stone-400 hover:text-white">View security posture <ChevronRight size={14} /></button></aside>
      <section className="relative min-h-[560px] overflow-hidden px-4 py-6 md:px-8"><div className="absolute inset-0 opacity-35 [background-image:linear-gradient(rgba(255,255,255,.045)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.045)_1px,transparent_1px)] [background-size:46px_46px]" /><div className="relative z-10 flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-stone-500">Attack intelligence</p><h2 className="mt-1 text-lg font-medium">Global activity</h2></div><span className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-emerald-300"><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400" />Live</span></div><div className="relative z-10 mt-2 h-[455px]"><GlobalAttackMap /></div><div className="relative z-10 flex justify-between border-t border-white/[.07] pt-4 text-[10px] uppercase tracking-wider text-stone-500"><span>06 active attack paths</span><span>Last event: just now</span></div></section>
      <aside className="border-t border-white/[.08] p-5 xl:border-l xl:border-t-0"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-stone-500">Live incident stream</p><AlertTriangle size={15} className="text-[#c97948]" /></div><div className="mt-5 divide-y divide-white/[.07]">{events.map(([ip,title,target,severity], index) => <motion.div key={ip} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .12 }} className="py-4"><div className="flex items-center justify-between"><span className="font-mono text-[11px] text-stone-300">{ip}</span><span className="text-[10px] capitalize" style={{ color: severity === 'critical' ? '#b94747' : severity === 'high' ? '#c97929' : '#b08a2e' }}>{severity}</span></div><p className="mt-2 text-sm">{title}</p><p className="mt-1 text-[11px] text-stone-500">Target: {target}</p></motion.div>)}</div><div className="mt-7 border-t border-white/[.07] pt-5"><div className="flex items-center gap-2 text-xs text-stone-300"><BrainCircuit size={15} className="text-[#c97848]" />AI analyst</div><p className="mt-2 text-xs leading-relaxed text-stone-500">Coordinated credential access behavior detected across two perimeter assets.</p><button className="mt-3 flex items-center gap-2 text-xs text-[#d8b17a]">Review analysis <ArrowDownRight size={14} /></button></div></aside>
    </div><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="border-t border-white/[.1] py-5"><div className="flex items-center gap-2 text-xs text-stone-400"><ShieldCheck size={15} className="text-emerald-400" />Detection coverage <b className="ml-auto font-medium text-stone-200">83%</b></div></div><div className="border-t border-white/[.1] py-5"><div className="flex items-center gap-2 text-xs text-stone-400"><AlertTriangle size={15} className="text-[#c97948]" />Mean time to detect <b className="ml-auto font-medium text-stone-200">4m 12s</b></div></div></div>
  </div>
}
