import { Link } from 'react-router-dom'
import { motion, useScroll, useSpring, useTransform } from 'framer-motion'
import { ArrowDown, ArrowUpRight } from 'lucide-react'
import { ThreatGlobe } from '@/components/ThreatGlobe'
import { ProjectNarrative } from '@/features/experience/ProjectNarrative'

const reveal = { initial: { opacity: 0, y: 32 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .35 }, transition: { duration: .7 } }

export function ExperiencePage() {
  const { scrollYProgress } = useScroll()
  const globeScale = useTransform(scrollYProgress, [0, .35], [1, .78])
  const smoothGlobeScale = useSpring(globeScale, { stiffness: 120, damping: 30, restDelta: .001 })
  return <main className="min-h-screen overflow-x-hidden bg-[#090a0b] text-[#f2eee8] selection:bg-[#8a3d3d]">
    <section className="relative min-h-screen overflow-hidden"><div className="absolute left-0 top-0 z-10 flex w-full items-center justify-between px-7 py-6"><span className="text-sm font-semibold tracking-tight">GOLDEN DOME <i className="ml-2 not-italic text-xs font-normal text-stone-500">/ by Salah</i></span><Link to="/login" className="rounded-full border border-white/15 px-4 py-2 text-xs text-stone-300 transition hover:bg-white hover:text-black">Enter workspace <ArrowUpRight className="ml-1 inline h-3.5 w-3.5" /></Link></div><motion.div style={{ scale: smoothGlobeScale, transformOrigin: 'center center' }} className="absolute inset-0"><ThreatGlobe /></motion.div><div className="pointer-events-none relative z-10 flex min-h-screen flex-col justify-end px-7 pb-12 md:px-16 md:pb-16"><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .4 }} className="mb-5 text-[11px] font-semibold uppercase tracking-[.2em] text-stone-500">AI-driven SOC platform · built by Salah Anez</motion.p><motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }} className="max-w-4xl text-5xl font-medium leading-[.95] tracking-[-.055em] md:text-8xl">One project.<br /><span className="text-stone-500">A global security view.</span></motion.h1><div className="mt-9 flex items-center gap-4 text-sm text-stone-400"><span className="h-px w-12 bg-stone-600" />Scroll to explore <ArrowDown className="h-4 w-4 animate-bounce" /></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-16 px-7 py-28 md:grid-cols-2 md:px-16"><motion.div {...reveal}><p className="eyebrow">A cybersecurity engineering portfolio project</p><h2 className="mt-4 text-4xl font-medium tracking-[-.04em]">Built to turn security telemetry into decisive action.</h2></motion.div><motion.div {...reveal} className="space-y-8 text-lg leading-relaxed text-stone-400"><p>Golden Dome is my end-to-end SOC platform: detection engineering, threat intelligence, local AI analysis, incident response, and approval-gated automation in one operational system.</p><div className="grid grid-cols-3 border-t border-white/10 pt-6 text-sm"><span><b className="block text-2xl text-[#c97848]">184</b>active paths</span><span><b className="block text-2xl text-[#b94747]">04</b>critical</span><span><b className="block text-2xl text-emerald-400">28</b>protected assets</span></div></motion.div></section>
    <ProjectNarrative />
    <section className="flex min-h-[70vh] items-center justify-center px-7 text-center"><motion.div {...reveal} className="max-w-3xl"><p className="eyebrow">About the builder</p><h2 className="mt-5 text-5xl font-medium tracking-[-.05em] md:text-7xl">Designed, built,<br />and secured by Salah Anez.</h2><p className="mx-auto mt-7 max-w-xl text-base leading-relaxed text-stone-400">Cybersecurity Engineering Student. Golden Dome is a hands-on demonstration of full-stack security engineering: building the controls, workflows, deployment model, and analyst experience—not just presenting the theory.</p><Link to="/login" className="mt-10 inline-flex items-center gap-2 rounded-full bg-[#e8e2d9] px-5 py-3 text-sm font-medium text-[#171717] transition hover:bg-white">Open SOC workspace <ArrowUpRight size={16} /></Link></motion.div></section>
  </main>
}
