import logging
from datetime import datetime
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import AdminUser, AnalystUser, CurrentUser
from app.database.database import get_db
from app.database.models import Alert, Asset, Incident, Report
from app.schemas.report import ReportCreate, ReportRead


from app.utils.datetime_helper import utc_now
logger = logging.getLogger(__name__)
router = APIRouter(prefix="/reports", tags=["Reports"])


@router.get("", response_model=dict)
async def list_reports(
    current_user: CurrentUser,
    db: AsyncSession = Depends(get_db),
    page: int = 1,
    limit: int = 20,
):
    total_result = await db.execute(select(Report))
    total = len(total_result.scalars().all())

    result = await db.execute(
        select(Report)
        .offset((page - 1) * limit)
        .limit(limit)
        .order_by(Report.created_at.desc())
    )
    reports = result.scalars().all()
    return {
        "data": [ReportRead.model_validate(r) for r in reports],
        "meta": {"page": page, "limit": limit, "total": total},
    }


@router.get("/{report_id}", response_model=ReportRead)
async def get_report(
    report_id: int,
    current_user: CurrentUser,
    db: AsyncSession = Depends(get_db),
):
    report = await db.get(Report, report_id)
    if not report:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")
    return report


@router.post("/generate", response_model=ReportRead, status_code=status.HTTP_201_CREATED)
async def generate_report(
    payload: ReportCreate,
    current_user: AnalystUser,
    db: AsyncSession = Depends(get_db),
):
    # Gather summary statistics for the report content.
    alert_count = (await db.execute(select(Alert))).scalars().all().__len__()
    incident_count = (await db.execute(select(Incident))).scalars().all().__len__()
    asset_count = (await db.execute(select(Asset))).scalars().all().__len__()

    content = (
        f"Golden Dome SOC Report: {payload.title}\n"
        f"Generated at: {utc_now().isoformat()} UTC\n"
        f"Generated by: {current_user.username}\n\n"
        f"Summary:\n"
        f"- Total alerts: {alert_count}\n"
        f"- Total incidents: {incident_count}\n"
        f"- Monitored assets: {asset_count}\n\n"
        f"{payload.content or ''}"
    )

    report = Report(
        title=payload.title,
        content=content,
        report_type=payload.report_type,
        created_by_id=current_user.id,
    )
    db.add(report)
    await db.commit()
    await db.refresh(report)
    logger.info("Report generated: %s by user %s", report.title, current_user.username)
    return report


@router.delete("/{report_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_report(
    report_id: int,
    current_user: AdminUser,
    db: AsyncSession = Depends(get_db),
):
    report = await db.get(Report, report_id)
    if not report:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")
    await db.delete(report)
    await db.commit()
    logger.info("Report deleted: %s by user %s", report.title, current_user.username)
    return None
